image: Visual Studio 2019

environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python37-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python38-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python39-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python310-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python310-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk17"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
